# Copyright 2025-2026 real-cis GmbH
# SPDX-License-Identifier: MIT

# Security
requirepass valkeypass
user default on >valkeypass ~* +@all -CONFIG -FLUSHALL -SHUTDOWN

# AOF
appendonly yes
appendfsync everysec
dir /data